name: cuycash
description: CuyCash — app móvil (banca digital · Perú).
publish_to: none
resolution: workspace
version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.6
  go_router: ^14.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.3.0
  supabase_flutter: ^2.8.0
  core_kernel:
    path: ../../packages/core_kernel
  design_system:
    path: ../../packages/design_system

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  freezed: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
